apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: headlamp-oidc-client-to-openbao
  namespace: keycloak
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao-push
      kind: ClusterSecretStore
  selector:
    secret:
      name: headlamp-oidc-client
  data:
    - match:
        secretKey: clientSecret
        remoteRef:
          remoteKey: platform/headlamp/oidc-client
          property: client-secret
