apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak.yaml
  - database.yaml
  - openbao-auth.yaml
  - openbao-database-bootstrap.yaml
  - realm-import.yaml
  - rbac.yaml
