apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
  - crossplane-provider.yaml
  - realm-import.yaml
  - identities.yaml
  - rbac.yaml
  - infisical-oidc.yaml
