apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  image: quay.io/keycloak/keycloak:26.7.3
  startOptimized: false
  bootstrapAdmin:
    user:
      secret: keycloak-operator-bootstrap
  db:
    vendor: postgres
    host: keycloak-db-rw
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-credentials
      key: username
    passwordSecret:
      name: keycloak-db-credentials
      key: password
  features:
    enabled:
      - client-admin-api:v2
  http:
    httpEnabled: true
  hostname:
    hostname: keycloak.platform.home.arpa
  proxy:
    headers: xforwarded
  ingress:
    enabled: true
    className: traefik
    tlsSecret: keycloak.platform.home.arpa-tls
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
