apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infisical
  namespace: flux-system
spec:
  interval: 1h
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: infisical-standalone
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: infisical-redis-values
      valuesKey: values.yaml
  values:
    infisical:
      replicaCount: 2
      kubeSecretRef: infisical-bootstrap
    postgresql:
      enabled: false
      useExistingPostgresSecret:
        enabled: true
        existingConnectionStringSecret:
          name: infisical-db-connection
          key: connection-string
    redis:
      enabled: true
      architecture: standalone
      master:
        persistence:
          enabled: true
          size: 5Gi
          storageClass: local-path
    ingress:
      enabled: true
      ingressClassName: traefik
      hostName: infisical.platform.home.arpa
      nginx:
        enabled: false
      tls:
        - secretName: infisical.platform.home.arpa-tls
          hosts:
            - infisical.platform.home.arpa
    ingress-nginx:
      enabled: false
