apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: capacitor-oauth2-proxy
  namespace: flux-system
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: capacitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: capacitor-oauth2-proxy
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-secret
      remoteRef:
        key: platform/capacitor/oidc-client
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: platform/capacitor/oidc-client
        property: cookie-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: capacitor-oidc-client
  namespace: keycloak
  labels:
    app.kubernetes.io/name: capacitor
    app.kubernetes.io/part-of: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: capacitor-oidc-client
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-secret
      remoteRef:
        key: platform/capacitor/oidc-client
        property: client-secret
